version: '2'
services:
  sensor:
    build: ./sensor
    networks: 
      sensor-controller:
        ipv4_address: 172.168.1.3
      sensor-monitor:
        ipv4_address: 172.168.0.3
    environment:
      PYTHONUNBUFFERED: 1
      PROD: 1
     
  controller:
    build: ./controller
    networks: 
      sensor-controller:
        ipv4_address: 172.168.1.5
      controller-monitor: 
        ipv4_address: 172.168.1.135
    environment:
      PYTHONUNBUFFERED: 1
      PROD: 1

  monitor: 
    build: ./monitor
    networks:
      controller-monitor:
        ipv4_address: 172.168.1.130
      sensor-monitor:
        ipv4_address: 172.168.0.5
      monitor-actuator:
        ipv4_address: 172.168.0.135
    environment:
      PYTHONUNBUFFERED: 1
      PROD: 1

  actuator:
    build: ./actuator
    networks:
      monitor-actuator:
        ipv4_address: 172.168.0.130
    environment:
      PYTHONUNBUFFERED: 1
      PROD: 1
    
networks:
  sensor-controller: 
    driver: bridge
    ipam:
     config:
       - subnet: 172.168.1.0/25

  controller-monitor: 
    driver: bridge
    ipam:
     config:
       - subnet: 172.168.1.128/25

  sensor-monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/25

  monitor-actuator:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.128/25